name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - API Endpoint
        - Authentication/Security
        - File Management
        - Program Execution
        - Voice Chat
        - Database/Storage
        - Monitoring/Logging
        - UI/Dashboard
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High (Critical functionality)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      options:
        - label: I am willing to implement this feature
        - label: I can provide additional details if needed
        - label: This is suitable for AI assistant implementation

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        As a [user type], I want to [do something] so that [goal]

  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: If this is an API feature, suggest the endpoint design
      render: json
      placeholder: |
        {
          "endpoint": "POST /api/new-feature",
          "request": {...},
          "response": {...}
        }

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      options:
        - label: This feature may introduce breaking changes

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
